// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljmegilfcuvmlxtvrhhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqbWVnaWxmY3V2bWx4dHZyaGhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDc2NzQsImV4cCI6MjA3MjgyMzY3NH0.3P-PSKel4lKCC0w2pJLsRXIMT5cIDpjIs_xBoQFe0IA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});