// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpqeqiudgqbzondtzqgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcWVxaXVkZ3Fiem9uZHR6cWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzYzOTAsImV4cCI6MjA3MjgxMjM5MH0.ozhYj16bmp10xi_jbtxLtDy9WVd0wrzeXC2gINypMFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});